# menu:
#   Home: /
#   About: /about
# font:
#   body: "Roboto"

# title: "我的技术博客" # 博客标题
# subtitle: "测试副标题" # 副标题
# description: "（搜索引擎抓取" # 描述（搜索引擎抓取）

# Site Information
site:
  name:
    class: text # text / i_class / img
    custom: Solitude # Solitude / fas fa-ghost / /img/pwa/favicon.ico
  icon: /img/favicon.jpg # Site icon / 网站图标